Project1/Project1/urls.py
from django.contrib import admin
from django.urls import include, path
#from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('general.urls')),
    path('check/', include('adult.urls')),
    path('tasks/', include('tasks.urls'))
]

Project1/adult/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),

    ]

Project1/general/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about),
    path("contacts", views.contacts),
    path("<str:name>", views.greeting, name="greeting"),

]

Project1/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

Project1/tasks/models.py
from django.db import models

# Create your models here.

Project1/adult/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    age = 18
    return render(request, "adult/index.html", {
        "age": True
    })

Project1/general/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "general/index.html")

def about(request):
    return render(request, "general/about.html")

def contacts(request):
    return render(request, "general/contacts.html")

def greeting(request, name):
    return render(request, "general/greeting.html", {
        "name": name.capitalize()
    })

Project1/tasks/views.py
from django.shortcuts import render

tasks = ["foo", "bar", "baz"]
# Create your views here.
def index(request):
    return render(request, "tasks/index.html", {
        "tasks": tasks
    })

def add(request):
    return render(request, "tasks/add.html")

Project1/adult/templates/adult/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Are you adult?</title>
</head>
<body>
    <form action="">
        <input type="text" placeholder="Введіть свій вік?">
    </form>
    <h1>Вам {{age}}</h1>
    <!-- <h1>Вам виповнилось 18 років</h1>
    <h1>Вам не виповнилось 18 років</h1> -->

    {% if age >= 18 %}
        <h1>Вам виповнилось 18 років</h1>
    {% else %}
        <h1>Вам не виповнилось 18 років</h1>
    {% endif %}
</body>
</html>

Project1/general/templates/general/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django-site</title>
    <link rel="stylesheet" href="{% static 'general/about.css' %}">
</head>
<body>
    <h1>About Us</h1>

</body>
</html>

Project1/general/templates/general/contacts.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Djang-site</title>
    <link rel="stylesheet" href="{% static 'general/contacts.css' %}">
</head>
<body>
    <h1>Contacts</h1>

</body>
</html>

Project1/general/templates/general/greeting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Greeting!</title>
    <link rel="stylesheet" href="{% static 'general/styles.css' %}">
</head>
<body>
    <h1>Hello, {{name}}!</h1>

</body>
</html>

Project1/general/templates/general/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django-site</title>
</head>
<body>
    <h1>Welcome to Django-site</h1>
</body>
</html>

Project1/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}
{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}">
        <input type="text" name="task">
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

Project1/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{task}}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a New Tasks</a>
{% endblock %}

Project1/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>

<body>
    {% block body %}
    {% endblock %}
</body>
</html>